<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0BGE448" failures="1" tests="2" name="RegressionTest" time="4.41" errors="0" timestamp="30 Jan 2022 06:03:32 GMT">
  <testcase classname="BankingTestCases.AddPayee2" name="login" time="2.368"/>
  <testcase classname="BankingTestCases.AddPayee2" name="addPayee" time="1.378">
    <failure type="java.lang.AssertionError" message="expected [The new payee saritha was successfully created1223.] but found [The new payee saritha was successfully created.]">
      <![CDATA[java.lang.AssertionError: expected [The new payee saritha was successfully created1223.] but found [The new payee saritha was successfully created.]
	at BankingTestCases.AddPayee2.addPayee(AddPayee2.java:75)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addPayee -->
</testsuite> <!-- RegressionTest -->
